apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mmsp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/example/mini-model-serving-platform.git
    targetRevision: HEAD
    path: k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: mmsp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
